[package]
name = "sound"
version = "0.1.0"
authors = [
	"Jeron A. Lau <jeron.lau@plopgrizzly.com>"
]

[dependencies]
rand = "0.5"

[dev-dependencies]
alsa = { path = "../alsa-rs", default-features = false, features = ["speaker"] }
